require 'plugins.utils'
require 'plugins.dashboard'
require 'plugins.ui'
require 'plugins.editor'
require 'plugins.navigation'
require 'plugins.mini'
require 'plugins.format'
require 'plugins.lsp'
require 'plugins.git'
require 'plugins.snacks'
require 'plugins.toggleterm'
require 'plugins.lint'

require 'plugins.overseer'
