require 'plugins.utils'
require 'plugins.treesitter'
require 'plugins.ui'
require 'plugins.dashboard'
require 'plugins.editor'
require 'plugins.navigation'
require 'plugins.mini'
require 'plugins.completion'
require 'plugins.format'
require 'plugins.lint'
require 'plugins.lsp'
require 'plugins.git'
require 'plugins.snacks'
require 'plugins.toggleterm'
require 'plugins.misc'

require 'plugins.overseer'
require 'plugins.kulala'

require 'plugins.markdown'
